# Generated by Django 4.0.5 on 2023-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_student_address_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Active', max_length=8),
        ),
    ]
